
version: '3.0'

services:

  practica3:
    image: cvlolox/pr
    restart: always
    build: ./practica3
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 practica3:app


  nginx:
    image: cvlolox/nginx
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - practica3
