
version: '3'

services:

  dash_app:
    container_name: practica3
    restart: always
    build: ./practica3
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 practica3:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
- practica3
