
version: '2'

services:

  practica3:
    container_name: practica3
    restart: always
    build: ./practica3
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 practica3:app


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - practica3
